services:
  - type: web
    name: smoother-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
